### ISSUE TITLE
Feature: Gloomy Puppet Show Select

### ISSUE THREAD

**Issue by NBeing** [BornPosthumous/VSAV_Training#19]
Allow Lilith players to choose Gloomy Puppet Show pattern.

From Kyle:
To allocate the PuppetShow pattern, we would have to directly alter the RNG RAM address. That would be tricky and have other unwanted effects.
Maybe if we also tie it to the “projectile on screen” flag, it will only update when Lilith does Gloomy or puppet show. 
Guess that could get weird with her DF illusions tho.

**Comment by MBDesu** [comment]
Resolved by #49 #50 #51
